version: "3"

services:
  db:
    container_name: postgres
    image: postgres
    volumes:
      - ./pgdata:/var/lib/posgtresql/data
    restart: always
    ports:
      - "5432:5432"

  app:
    container_name: movie-rental-auth
    build: .
    restart: always
    links:
      - db
    ports:
      - "4000:4000"
